modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="turtken"
version="1.2.0"
displayName="Turtken"
displayURL="https://modrinth.com/mod/turtken"
logoFile="logo.png"
credits="Models by Bumstonaut"
authors="Jacob0225, Bumstronaut"
description="Enjoy Turtken"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.turtken]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.123,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.turtken]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration